### ISSUE TITLE
Gradle 3 - Cannot set the value of read-only property 'outputFile'

### ISSUE THREAD

**Issue by xni06** [gradle-fury/gradle-fury#54]
If I upgrade to use `com.android.tools.build:gradle:3.0.0-beta5` and `distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip`:

```
* Where:
Script '/Users/me/git/gradle-fury/gradle/android-support.gradle' line: 116

* What went wrong:
A problem occurred configuring project ':hello-world-aar'.
> Cannot set the value of read-only property 'outputFile' for object of type com.android.build.gradle.internal.api.LibraryVariantOutputImpl.
```

Does #51 include this issue? Thanks.

**Comment by spyhunter99** [comment]
hmmm haven't ran into this one yet. I'm not a fan of running beta versions of anything related to android or gradle

**Comment by ToxicBakery** [comment]
It's actually released now (AS3.x) and the Android 3.0.0 plugin. Unless anything has changed I believe this is still broken. I took a look at fixing it during one of the Alpha releases but I didn't see an obvious work around.

**Comment by spyhunter99** [comment]
Well we have to open a support ticket for the gradle plugin. Can you do it? 
In the mean time I can try catch this but I bet publishing the artifact with fail

**Comment by ToxicBakery** [comment]
I'll have to dig back into it, I was hoping they would just 'fix' it on their side but it looks like they are sticking with the implementation that broke fury. I'm going to have to figure it out for one of my projects using fury soon so I'll let post back when I figure out a solution or a more explainable problem.

**Comment by ToxicBakery** [comment]
Looking into it some, it appears the life cycle orders may have changed? I'm getting an error now for `Could not get unknown property 'isDistribution'` meaning the [pre evaluation section](https://github.com/gradle-fury/gradle-fury/blob/master/gradle/maven-support.gradle#L425) is not happening in the right order anymore. If I try to fix that, it seems to happen before the android library plugin is applied and we lose the ability to determine if the project is an android project or not while configuring publishing. So that's lovely.

I'm not really sure what to do here and I tried following some of the various issue links in the source to understand the process which I think I understand however that's no use as I do not know what the graph order is right now and seems like it's hell to debug for this situation.

Going back to the root problem defined by this issue, it is actually a really simple fix. Simply replace
```groovy
variant.outputs[0].outputFile = new File(apk.parentFile, artifactName);
```

with
```groovy
variant.outputs[0].outputFileName = artifactName
```

The API changes simply prevent you from mucking with the file object directly however they honor the name change request. This is actually a generally sensible change imo.

**Comment by spyhunter99** [comment]
i wonder what the backwards compatibility is for this.... test in progress

**Comment by spyhunter99** [comment]
> Could not set unknown property 'outputFileName' for object of type com.android.build.gradle.internal.api.LibraryVariantOutputImpl.

so they just changed the api entirely. No backwards compat.

**Comment by ToxicBakery** [comment]
yeah but i think it would be alright to say 'this is breaking' considering all the various build changes in 3.x

**Comment by spyhunter99** [comment]
on a whim, i told travis to rebuild develop, which hasn't been altered in a while, naturally we have build failures. They apparently have no republishing artifacts over and over again

**Comment by ToxicBakery** [comment]
Yikes, if it would be helpful I can build a docker image for running the fury builds for you. That takes out the issues with 'does it work on travis'. If you're interested it looks like this:

https://github.com/Rajawali/Rajawali/commit/05c26e88731f76ca97b4ccde9e1c76a5060d94b1

**Comment by spyhunter99** [comment]
the travis setup is always a clean build with no cache at all. if it works one day and not the next, some dependency was republished. the google folks tend to do this from time to time. sometimes the republish is ok, other time it break stuff. there appears to be little in the ways of quality control and ci testing

**Comment by spyhunter99** [comment]
@ToxicBakery let's make new tickets for the other issues. sounds like there's more going on than just the output filename
